### ISSUE TITLE
Looking forward to the code!

### ISSUE THREAD

**Issue by thaoshibe** [wty-ustc/e2style#1]
I've just read through your paper and it's superb.
I created this issue just to say that I'm looking forward to your code.
Hope you can release the code soon!

**Comment by wtybest** [comment]
Once our paper is accepted, we will release the code and pre-trained models. Please stay tuned.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wty-ustc/StyleGAN-Inversion-Baseline"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月19日(星期一) 中午11:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wty-ustc/StyleGAN-Inversion-Baseline] Looking forward to code! (#1)





 
I've just read through your paper and it's superb.
 I created this issue just to say that I'm looking forward to your code.
 Hope you can release the code soon!
