### ISSUE TITLE
UnboundLocalError: local variable 'images' referenced before assignment

### ISSUE THREAD

**Issue by c1a1o1** [wty-ustc/e2style#10]
F:\ProgramData\Anaconda3\python.exe F:/work/mingxingshipin/opencv_Real_Time_Image_Animation-master/e2style-main/scripts/inference.py
Inference: Results are from Stage1.
Loading E2Style from checkpoint: F:/work/mingxingshipin/opencv_Real_Time_Image_Animation-master/e2style-main/pretrained_models/sr.pt
Loading dataset for celebs_super_resolution
Performing down-sampling with factors: [1, 2, 4, 8, 16, 32]
  0%|          | 0/4 [00:25<?, ?it/s]
Traceback (most recent call last):
  File "F:/work/mingxingshipin/opencv_Real_Time_Image_Animation-master/e2style-main/scripts/inference.py", line 120, in <module>
    run()
  File "F:/work/mingxingshipin/opencv_Real_Time_Image_Animation-master/e2style-main/scripts/inference.py", line 77, in run
    result_batch, latent_batch = net(input_cuda, randomize_noise=False, resize=opts.resize_outputs, return_latents=True)
  File "F:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "..\models\e2style.py", line 100, in forward
    return images, result_latent
UnboundLocalError: local variable 'images' referenced before assignment

**Comment by wtybest** [comment]
After seeing issue #11 , I believe you have solved the problem.

**Comment by c1a1o1** [comment]
Thanks very much!

**Comment by Dratlan** [comment]
> After seeing issue #11 , I believe you have solved the problem.

uhhh, I'm a little confused. Is that related to this? I solve this question by reset resize=true. By the way, why the output of super resolution always got 256*256(I didn't choose the --resize_outputs)
