### ISSUE TITLE
Super resolution got bad results, can you give some advice? The original image is just a problem with the mouth. After super-resolution, it has some male characteristics.

### ISSUE THREAD

**Issue by c1a1o1** [wty-ustc/e2style#11]
Super resolution got bad results, can you give some advice? The original image is just a problem with the mouth. After super-resolution, it has some male characteristics.

Actually only the mouth area needs to be optimized
![10001](https://user-images.githubusercontent.com/7991905/155907349-2d858dee-d125-4fc9-a128-0bfe7c85d387.jpg)
![10003](https://user-images.githubusercontent.com/7991905/155907362-974b444f-8aa0-47eb-b160-28a72a7f9f22.jpg)
![10004](https://user-images.githubusercontent.com/7991905/155907364-00f565e2-019d-4361-99ab-494974975bd0.jpg)
![10005](https://user-images.githubusercontent.com/7991905/155907366-d03c9f34-9f88-4ee5-b5fb-aee1f340ac0e.jpg)
![10006](https://user-images.githubusercontent.com/7991905/155907367-345d3c9e-fb0a-4c22-820b-ecad04cae307.jpg)
![10007](https://user-images.githubusercontent.com/7991905/155907368-db215654-0217-4f45-af02-bc1b3d31afcf.jpg)
![10021](https://user-images.githubusercontent.com/7991905/155907369-957eaae7-15ca-4c7f-98e5-5fdfe2357cba.jpg)

**Comment by wtybest** [comment]
In fact, our super-resolution model is trained with the goal of generating plausible results given an overall low-resolution image, and from this perspective, it performs well. For your needs, I think you can look for other methods of local super-resolution or modify the data augmentation in https://github.com/wty-ustc/e2style/blob/fe110b3c71b94f9297c48a12f78ec7df76a8e35a/configs/transforms_config.py#L119 to train a local super-resolution model for the lip region.
