### ISSUE TITLE
代码呢？两个月过去了 

### ISSUE THREAD

**Issue by TomatoBoy90** [wty-ustc/e2style#2]

**Comment by wtybest** [comment]
我不知道您是没看到readme最前面高亮的那句话，还是看不懂英语。帮您翻译一下：一旦我们的论文被接收，我们会立刻开源代码和预训练模型。
另外，送您一句话共勉：从容不迫的举止比起咄咄逼人的态度更能令人心折。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月6日(周日) 上午10:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wty-ustc/StyleGAN-Inversion-Baseline] 代码呢？两个月过去了  (#2)

**Comment by TomatoBoy90** [comment]
您是对立刻有啥误解？

**Comment by wtybest** [comment]
我们还没中稿，预计7月底出结果。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月6日(周日) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wty-ustc/StyleGAN-Inversion-Baseline] 代码呢？两个月过去了  (#2)




 
您是对立刻有啥误解？

**Comment by welbeckzhou** [comment]
> 您是对立刻有啥误解？

这位朋友有点个性啊，第一次见要代码要得这么理直气壮还不懂礼貌的，我觉得按照您这个底气自己复现也不是什么难事儿吧

**Comment by 8secz-johndpope** [comment]
@TomatoBoy90 - fsgan weights https://github.com/aayushrai/GAN/blob/master/FaceSwap/weights/download_fsgan_models.py

**Comment by FDU-WeiXiZhang** [comment]
祝顺利接收~

**Comment by wtybest** [comment]
> 祝顺利接收~

谢谢！
