### ISSUE TITLE
How to provide test images for inpainting

### ISSUE THREAD

**Issue by c1a1o1** [wty-ustc/e2style#9]
Great work！How to provide test images for inpainting

**Comment by wtybest** [comment]
As shown below: https://github.com/wty-ustc/e2style/blob/fe110b3c71b94f9297c48a12f78ec7df76a8e35a/datasets/images_dataset.py#L55
You can create test images using our simple data augmentation in the training phase, or you can create test images in other ways, just make sure that the rgb value of the area to be inpainted in the aligned image is 0.

**Comment by c1a1o1** [comment]
Thanks very much!
